"""ACM is tested against a panel generated by the affine model it claims to invert.

The generator below deliberately does not import the module's own recursion: if the two
shared a sign error the tests would agree with the bug and prove nothing. It is written
out again from the pricing equations, which is the one place in this repository where
duplicating a dozen lines earns its keep.
"""

import numpy as np
import pytest

from rlab.errors import ModelError
from rlab.termpremium.acm import MIN_OBSERVATIONS, estimate

MATURITIES = np.arange(1, 121, dtype=float)
TEN_YEAR = -1  # last column of a 1..120 month grid

TRANSITION = np.diag([0.995, 0.96, 0.90])
INNOVATION_SCALE = np.diag([0.0030, 0.0020, 0.0012])
SHORT_RATE_INTERCEPT = 0.04 / 12
SHORT_RATE_LOADINGS = np.array([1.0, -0.6, 0.3]) / 12
RISK_DIRECTION = np.array([1.0, 0.5, -0.2])


def _log_prices(drift, transition, factors):
    """Affine recursion, written from the pricing equations rather than imported."""
    sigma = INNOVATION_SCALE @ INNOVATION_SCALE.T
    a_n, b_n = -SHORT_RATE_INTERCEPT, -SHORT_RATE_LOADINGS
    a_all, b_all = np.empty(MATURITIES.size), np.empty((MATURITIES.size, 3))
    a_all[0], b_all[0] = a_n, b_n
    for n in range(1, MATURITIES.size):
        a_next = a_n + b_n @ drift + 0.5 * (b_n @ sigma @ b_n) - SHORT_RATE_INTERCEPT
        b_next = transition.T @ b_n - SHORT_RATE_LOADINGS
        a_n, b_n = a_next, b_next
        a_all[n], b_all[n] = a_n, b_n
    return a_all[None, :] + factors @ b_all.T


def affine_panel(months: int, seed: int, price_of_risk: float, noise_bp: float = 0.0):
    """A three-factor affine curve panel with a known, controllable term premium.

    Returns the observed panel and the term premium that generated it, both in decimals.
    """
    rng = np.random.default_rng(seed)
    lambda0 = RISK_DIRECTION * price_of_risk

    factors = np.zeros((months, 3))
    for t in range(1, months):
        factors[t] = TRANSITION @ factors[t - 1] + INNOVATION_SCALE @ rng.normal(size=3)

    priced = -_log_prices(-lambda0, TRANSITION, factors) / MATURITIES * 12
    expected = -_log_prices(np.zeros(3), TRANSITION, factors) / MATURITIES * 12
    observed = priced + rng.normal(scale=noise_bp * 1e-4, size=priced.shape)
    return observed, priced - expected


def test_the_decomposition_is_an_identity_by_construction():
    panel, _ = affine_panel(400, seed=0, price_of_risk=0.002)
    result = estimate(panel, MATURITIES)
    assert np.allclose(result.term_premium, result.fitted - result.risk_neutral, atol=1e-15)


def test_the_fitted_curve_reprices_a_panel_the_model_itself_generated():
    """Under no observation noise the fit is a numerical identity, not an approximation."""
    panel, _ = affine_panel(400, seed=1, price_of_risk=0.002)
    result = estimate(panel, MATURITIES)
    worst_bp = np.max(np.abs(result.fitted - panel)) * 1e4
    assert worst_bp < 1.0


def test_observation_noise_degrades_the_fit_in_proportion_and_no_worse():
    """Real curves are not exactly affine, so the fit has to fail gracefully, not blow up."""
    panel, _ = affine_panel(400, seed=2, price_of_risk=0.002, noise_bp=2.0)
    result = estimate(panel, MATURITIES)
    worst_bp = np.max(np.abs(result.fitted - panel)) * 1e4
    assert worst_bp < 20.0


def test_the_estimated_ten_year_premium_recovers_the_one_that_generated_the_panel():
    panel, true_premium = affine_panel(1200, seed=3, price_of_risk=0.002)
    result = estimate(panel, MATURITIES)
    estimated_bp = result.term_premium.mean(axis=0)[TEN_YEAR] * 1e4
    true_bp = true_premium.mean(axis=0)[TEN_YEAR] * 1e4
    assert abs(estimated_bp - true_bp) < 0.15 * abs(true_bp)


def test_a_panel_with_no_price_of_risk_leaves_only_the_small_sample_bias():
    """Set the true premium to zero and what is left is the estimator's own resolution."""
    panel, true_premium = affine_panel(1200, seed=4, price_of_risk=0.0)
    assert np.allclose(true_premium, 0.0, atol=1e-12)
    result = estimate(panel, MATURITIES)
    estimated_bp = abs(result.term_premium.mean(axis=0)[TEN_YEAR] * 1e4)
    assert estimated_bp < 100.0


def test_a_larger_price_of_risk_produces_a_larger_premium():
    small, _ = affine_panel(1200, seed=5, price_of_risk=0.001)
    large, _ = affine_panel(1200, seed=5, price_of_risk=0.004)
    small_bp = abs(estimate(small, MATURITIES).term_premium.mean(axis=0)[TEN_YEAR])
    large_bp = abs(estimate(large, MATURITIES).term_premium.mean(axis=0)[TEN_YEAR])
    assert large_bp > 2.0 * small_bp


def test_the_ten_year_term_premium_is_a_finite_series_of_the_right_length():
    panel, _ = affine_panel(400, seed=6, price_of_risk=0.002)
    result = estimate(panel, MATURITIES)
    ten_year = result.term_premium[:, TEN_YEAR]
    assert ten_year.shape == (400,)
    assert np.all(np.isfinite(ten_year))


def test_a_short_panel_raises_rather_than_estimating_a_var_on_nothing():
    panel, _ = affine_panel(MIN_OBSERVATIONS - 1, seed=7, price_of_risk=0.0)
    with pytest.raises(ModelError, match="monthly observations"):
        estimate(panel, MATURITIES)


def test_more_factors_than_maturities_raises():
    panel, _ = affine_panel(200, seed=8, price_of_risk=0.0)
    with pytest.raises(ModelError, match="cannot extract"):
        estimate(panel[:, :4], MATURITIES[:4], n_factors=9)


def test_a_panel_with_missing_values_raises():
    panel, _ = affine_panel(200, seed=9, price_of_risk=0.0)
    panel[10, 2] = np.nan
    with pytest.raises(ModelError, match="missing"):
        estimate(panel, MATURITIES)


def test_a_maturity_grid_with_holes_raises_rather_than_interpolating_silently():
    panel, _ = affine_panel(200, seed=10, price_of_risk=0.0)
    gappy = np.array([3, 12, 24, 60, 84, 120], dtype=float)
    with pytest.raises(ModelError, match="monthly maturity grid"):
        estimate(panel[:, :6], gappy)
